### PR TITLE
Emphasize forum via button

### PR DESCRIPTION
**Pull request by rosano**
Screen Shot 2021-08-31 at 10 47 16

### CODE REVIEW

**Comment by raucao** [comment]
Could we move this up, perhaps to just before the table of other community venues/places?

**Comment by rosano** [comment]
Done, but I recommend it at the end to maintain the visual rhythm started by the other sections. When it 'wraps around' the contributor list, it's like a hug, otherwise it ends a bit coldly.

**Comment by rosano** [comment]
Done.

**Review by raucao — APPROVED** [review]
thanks-ht

**Comment by rosano** [comment]
I think the extra copy was useful to emphasize that all kinds are welcome and also to have some visual contrast in how the other call-to-actions are presented. It's a bit terse as this button is a social invitation, unlike the others.

**Comment by rosano** [comment]
@raucao Would you mind leaving your feedback on my comment so it's documented? Not sure why take out that kind of text.

**Comment by raucao** [comment]
Sure, I was just leaving the computer for that day when I saw it and didn't have the time to reply, then forgot about it.

When I reviewed the page, I had originally intended to just leave it and merge. But the layout was completely off, with the sentence not rendering vertically centered in line with the button, but way on the bottom line of it. I then tried to fiddle with the styles to make it render nicely, and didn't succeed in a reasonable amount of time. So I removed it, as it's exactly the same as in the table/list above anyway.

**Comment by rosano** [comment]
@raucao I wonder why it's different than my screenshot or if there's anything else that's different. What browser are you using?

**Comment by raucao** [comment]
Firefox stable. Good question.

**Comment by rosano** [comment]
I can confirm the issue on Firefox and managed to fix it by removing the `.my-4` class from the button (which was creating extra vertical space), and using `align-items: center`. As I mentioned, I feel it's important to have some warmth near that button as it's a social invitation. Not sure how to add to this pull request so I posted in #64. 

Whether it gets merged or not, I would like to communicate that it's kind of demotivating to have half the pull request stripped out without explaining why it's preferable; when asked, you essentially rephrase your commit message ('extra text'). Although it might not be obvious, there was thought put into why it's arranged that way. I think when you make suggestions, I make an effort to do them while also explaining my point-of-view. Sometimes your way of communicating comes across as aloof to me, although I don't think you mean it that way.

**Comment by raucao** [comment]
Why would it not get merged? When you asked about why I left it out, I only explained what happened, without arguing anything. The comment about why you think it's important hadn't been written yet when I merged. I had stated before _"I guess we could remove the extra sentence after the button then, too, so it would be exactly like the other call-to-action buttons"_, and as there was no reply to that, I simply took that as a neutral ACK without disagreement (green light either way).

However, the misunderstanding was then exacerbated by me not marking the new feedback as something to resolve the next day, because it didn't contain a question, and was neither something that could be resolved in the same PR at that point. As I said, I had seen the comment after a long day of work, and was about to leave my computer for the day, literally the minute I saw the additional feedback.

So yeah, I'm sorry that I did not address your feedback! I definitely didn't mean to ignore it. And I acted in good faith when removing the paragraph, not trying to change something you would disagree with.

Overall, this is obviously a fine line to walk in general. If we re-review every change and detail added to every PR before merging, then we'll spend a lot of time on doing that and less time changing things (which I think we all like better). On the other hand, we obviously also need to address everything in some way, if and when it's brought up. Sometimes this will fail, for one of many possible reasons. In which case, as you also just did, let's always assume good faith on all sides. And let's also try to resolve things efficiently, and ideally discuss personal communication issues in private conversations, outside of GitHub threads.

**Comment by rosano** [comment]
> and as there was no reply to that, I simply took that as a neutral ACK without disagreement

I can see how you understood that. I guess if I agreed I could have taken it out myself. I forgot about that point and was focused on the other two things, so I ended up not mentioning it.

> discuss personal communication issues in private conversations, outside of GitHub threads.

Ok.

**Pull request merged**
