### PR TITLE
Merge website and wiki

### PR DESCRIPTION
**Pull request by rosano**
This is still in progress, lots of broken links abound but basically it's a functional/deployable version of the site with [all the wiki content](https://wiki.remotestorage.io/Special:AllPages).

Live version: https://rosano.github.io/website

See forum discussion: https://community.remotestorage.io/t/remotestorage-monthly-hangout-august-2021/708

### CODE REVIEW

**Comment by rosano** [comment]
This is still in progress, lots of broken links abound but basically it's a functional/deployable version of the site with all the content from the wiki.

**Comment by rosano** [comment]
> The table of apps has to be scrolled horizontally to see the rightmost column, even when the window has unused width: https://rosano.github.io/website/docs/apps/

That how https://github.com/pmarsceill/just-the-docs renders tables at the moment. The CSS could be tweaked but I think the apps will eventually be something other than that large table—for now I just copied the content over so that the wiki can be purged.

**Comment by rosano** [comment]
There is a nice way to [render contributors](https://pmarsceill.github.io/just-the-docs/#contributing), but if I implemented it here it might be those who committed in the website repo. Would it make sense to move this whole thing to the remotestorage.js repo so we can show those contributors on the website?

**Comment by rosano** [comment]
Any one else want to comment on this? @raucao I'm not sure who else to tag/ask here.

**Comment by raucao** [comment]
I think this direction makes sense. :+1:

**Comment by rosano** [comment]
> There is a nice way to [render contributors](https://pmarsceill.github.io/just-the-docs/#contributing), but if I implemented it here it might be those who committed in the website repo. Would it make sense to move this whole thing to the remotestorage.js repo so we can show those contributors on the website?

@raucao are you referring to this or the initial post? I'm inclined to move all this to remotestorage.js and continue there.

**Comment by raucao** [comment]
Ah sorry, I was referring to the initial post and nature of the PR.

remoteStorage.js has its own repo and an existing, fully working documentation website. This website and the wiki content are about the general protocol that is remoteStorage. But if there is library-specific content left somewhere, then we can transfer that to the appropriate place, of course. I think some wiki pages have already been superceded by rs.js prose docs (e.g. "Beginners" by "Getting Started").

**Comment by rosano** [comment]
Changes so far:
- it seems that by setting a custom domain in GitHub Pages, the links are working properly, for example <https://rs.rosano.ca>.
- Contributors are displayed on the front page.
- Benefits from #16 are in the features list.
- There is a 'Get storage' link in the first section pointing to /servers

I think this is a great improvement on the current site. What else needs to be done before merging this? I think #9, #16, #53, and #57 can be closed.

**Comment by raucao** [comment]
Great!

> Benefits from #16 are in the features list.

I think it would make sense to expcliticly group those under sections "For users" and "For app developers"

> What else needs to be done before merging this?

* Reviewing all content, deleting obsolete pages (like the beginners one I mentioned), and moving unstructured things like notes to more appropriate places.
* If we want to show contributors on the new website, then I think it should include as many as we can collect from all pieces of RS software that we know of. Currently, it seems to be only the ones from the website repo. As stated above, the rs.js repo that was suggested for this content to be moved to, is not a general RS protocol repo, so this website will still be different from that, and thus not include the rs.js contributors.
* Improving the layout on the "protocol" page (which actually includes an explanation of general Unhosted architecture, so maybe split that out). In my opinion, it is currently a step down from what we have online at the moment, as it's more difficult to grasp the information like this.

For the wiki pages, instead of moving/fixing everything directly, we could also add a sentence on the index page to explain why the content is included like that on the website, so that someone looking at the new website knows what's going on.

**Comment by rosano** [comment]
Changes so far:
- Show "Edit this page on GitHub" links
- Group features by users and developers
- Alert that wiki pages are being revised, better to consult rs.js docs. Considering they were all written by people other than myself, I'm not sure what's what.

> If we want to show contributors on the new website, then I think it should include as many as we can collect from all pieces of RS software that we know of. Currently, it seems to be only the ones from the website repo. As stated above, the rs.js repo that was suggested for this content to be moved to, is not a general RS protocol repo, so this website will still be different from that, and thus not include the rs.js contributors.

Does anyone else from @remotestorage/core have opinions about this?

> Improving the layout on the "protocol" page (which actually includes an explanation of general Unhosted architecture, so maybe split that out). In my opinion, it is currently a step down from what we have online at the moment, as it's more difficult to grasp the information like this.

I capped the size of the images so it's easier to see the headings—it was a bit unwieldy. At the moment, I'm trying to just move content over and avoid writing anything, although I did re-word the image captions because they would have been out of place in this layout. This whole page needs to be re-thought with a holistic concept of what we're trying to communicate. I can work on this over time, but maybe we can just keep the previous content for now?

**Comment by raucao** [comment]
Could you perhaps re-open this with a branch directly on this repo? Otherwise we cannot collaborate on the source...

**Comment by rosano** [comment]
Closing to continue in #59

**Comment by raucao** [comment]
Great, thanks.

**Pull request closed without merging**
