### PR TITLE
Redo explainer graphics with yed

### PR DESCRIPTION
**Pull request by untitaker**

### CODE REVIEW

**Comment by skddc** [comment]
I added a text legend to the current items, which solves the problem as well, and is a bit more explicit even. Check it out and let me know if you would still prefer new graphics.

**Comment by untitaker** [comment]
Why not both? :)

**Comment by skddc** [comment]
I think the current graphics are simpler and easier to understand, in combination with the legend.

**Comment by untitaker** [comment]
I think it's important to point out which components are owned by which parties (which is why I mentioned the dotted lines in IRC), and also clarify the difference between "storage provider" and "clientside" in the last picture.

**Comment by skddc** [comment]
> I think it's important to point out which components are owned by which parties (which is why I mentioned the dotted lines in IRC),

Yes, that's why I used the colors and literal explanation.

> and also clarify the difference between "storage provider" and "clientside" in the last picture.

You can be your own provider, but regardless of wording there I think it's clear that the "data" thing is different than the client-side in the existing version, and it is also explained in the captions.

**Comment by skddc** [comment]
If we can't come to a consensus easily, we could post screenshots of both versions and ask some more people for their opinions.

**Comment by jancborchardt** [comment]
If you post screenshots I can give a quick comment. :)

**Comment by untitaker** [comment]
Before:

2016-01-08-200906_1015x548_scrot

After:

2016-01-08-200840_1026x570_scrot

**Comment by untitaker** [comment]
Edited previous post to include new master version.

**Comment by jancborchardt** [comment]
I'd say the new master version is the best. The color and clear layout does a very quick job of explaining the differences.

**Comment by untitaker** [comment]
Fair enough.

**Pull request closed without merging**
