### PR TITLE
Migrate to VitePress, include rs.js docs

### PR DESCRIPTION
**Pull request by raucao**
See https://community.remotestorage.io/t/new-website-and-rs-js-documentation-site/850 for details and https://rs-website-preview.5apps.com/ for current live preview.

### CODE REVIEW

**Comment by raucao** [comment]
I think we're done for this PR, not withstanding further improvements afterwards.

See the updated [README](https://github.com/remotestorage/website/blob/b13a8315b9273725332eacd4e8f5381e992db6de/README.md) for instructions for local previews.

I added a GitHub action, which should deploy the new website to GitHub pages once this PR is merged, and then whenever the `master` branch is updated.

**Comment by DougReeder** [comment]
In order to run `git submodule update --init`, you must have have a public SSH key associated with your GitHub account.  That's a reasonable requirement, but it needs to be documented.

**Comment by raucao** [comment]
@DougReeder resolved in the latest commit.

**Review by DougReeder — APPROVED** [review]
It looks good.  As soon as the instructions at `rs.js/docs/contributing/docs.html` are replaced, we're good to go.

**Comment by raucao** [comment]
@DougReeder OK, thanks. Opened https://github.com/remotestorage/remotestorage.js/pull/1317 for it.

I edited it directly on GitHub, just to test that it's possible/easy to contribute docs changes without even setting up the local preview.

**Comment by raucao** [comment]
I fixed a few minor issues directly on master after merging this PR. We're live!

**Pull request merged**
